- server/controllers/entities/search_by_text.coffee
This bug occurred when I tried adding a book with an empty ES. The fix catches all the "not found" errors and ignores them.
> Do not error on "not found" search results.

- .gitignore
- config/universal_path.coffee
- package.json
- scripts/actions/backup_databases.coffee
- scripts/actions/lib/backup_database.coffee
- scripts/actions/lib/zip_backup_folder.coffee
- scripts/dumps/convert_ndjson_dump_to_ttl
- scripts/dumps/headers.ttl
- scripts/dumps/lib/serialize_entity_in_turtle.coffee
- scripts/dumps/prepare_entities_ndjson_dump
to be published on dumps.inventaire.io. Also unlocking the possibility to load a dump in a BlazeGraph instance
> Adding scripts to generate NDJSON and TTL dumps of the entity database

- api_tests/items/create.test.coffee
- package.json
- server/controllers/user/lib/update_snapshot_items_counts.coffee
`user.snapshot['items:last-add']` was never set, as `created > index[listing]['items:last-add']` was always false
> user snapshot: fixed items:last-add timestamp

- api_tests/entities/reverse_claims.test.coffee
- server/controllers/entities/lib/reverse_claims.coffee
namely wdt:P31
Motivations:
- no use case for knowing all the entities matching a given P31
- allowing to query all the instances of Q571 or Q5 sorted by popularity was making the server eat all the RAM
> entities: reverse claims: blacklisting properties with too many results

- server/db/couch/init.coffee
as the previous implementation using _.error was letting the process exit before logging anything
for unclear reasons
> couch init: simplify the error logging in case of wrong credentials

- package.json
- server/controllers/entities/lib/get_entity_type.coffee
- server/controllers/entities/lib/get_wikidata_enriched_entities.coffee
- server/controllers/entities/search_type.coffee
- server/lib/wikidata/whitelisted_properties.coffee
fallback on wdt:P279 claims values for Wikidata entities which type can't be identified from wdt:P31
ex: [Q28135131](https://www.wikidata.org/wiki/Q28135131) currently has a P279 claim that should make it be identified as a genre, but no P31. Consequently, adding it as a genre (wdt:P136) claim value is currently rejected by the editor
> Get entity type from wdt:P279

- server/controllers/entities/lib/update_search_engine.coffee
to let the [entities search engine unindex entities](https://github.com/inventaire/wikidata-subset-search-engine/commit/6aebcbc) that formerly had a known type
> send search engine update requests for entities with no known type

- config/default.coffee
- config/dev.coffee
- db/couchdb/design_docs/comments.json
- db/couchdb/design_docs/entities.json
- db/couchdb/design_docs/entities_deduplicate.json
- db/couchdb/design_docs/followedEntities.json
- db/couchdb/design_docs/groups.json
- db/couchdb/design_docs/invited.json
- db/couchdb/design_docs/items.json
- db/couchdb/design_docs/notifications.json
- db/couchdb/design_docs/patches.json
- db/couchdb/design_docs/relations.json
- db/couchdb/design_docs/transactions.json
- db/couchdb/design_docs/users.json
- server/db/couch/init.coffee
- server/db/couch/init_design_doc_sync.coffee
- server/db/couch/list.coffee
- server/lib/follow.coffee
Keep the design doc files in sync with CouchDB design docs once CouchDB design docs were updated to match the design doc files. This allows to modify design docs in CouchDB GUI instead of having
to change files manually, with all the formatting implied.
This only make sense in development.
> Design doc sync

- api_tests/entities/update_claims.test.coffee
- server/controllers/entities/lib/alias_uris.coffee
- server/controllers/entities/lib/entities.coffee
- server/controllers/entities/lib/properties.coffee
- server/controllers/entities/lib/properties_config_bases.coffee
- server/controllers/entities/lib/properties_config_builders.coffee
- server/controllers/entities/lib/validate_claim_value.coffee
- server/models/tests/common.coffee
- server/models/tests/group.coffee
- server/models/tests/item.coffee
- server/models/tests/user.coffee
- test/controllers/011-properties.coffee
- test/models/022-user.coffee
properties configuration object were a bit hard to read for new comers:
- splitted and restructed the main file
- removed the unnecessary `format: _.identity` functions
- took the occasion of cleaning a property config validation test to do some cleaning on string validation functions
> cleaning properties

- server/controllers/entities/lib/scaffold_entity_from_seed/edition.coffee
> edition entity scaffold: use a cache to prevent creating several entities with the same ISBN

- server/db/couch/init_hard_coded_documents.coffee
fixing issue of couch init update response `401 Unauthorized`
dependent of the length of `hardCodedDocuments` but update users sequetially
> sequential users setup

- server/controllers/feedback.coffee
- server/lib/emails/email.coffee
- server/lib/emails/send_email.coffee
- server/lib/emails/views/feedback.hbs
so that the email can generate links, very helpful for feedback such as 'possible work duplicate',
'entity type', or 'data error' automatic messages, where you have to open the associated entities pages to solve the reported issue
> feedback endpoint: allow to pass entity URIs

- api_tests/users/by_username.test.coffee
- server/controllers/user/lib/user.coffee
to prevent having keys mismatches: whatever the requested username case
the username used as keys are all returned lowercased
=> tolerant on the input, consistent on the output
> users: byUsername: index by lowercased username

- server/controllers/entities/lib/get_entities_popularity.coffee
- server/controllers/tasks/check_entities.coffee
- server/controllers/tasks/collect_entities.coffee
- server/controllers/tasks/lib/check_entity.coffee
- server/controllers/tasks/tasks.coffee
- tests/api/fixtures/entities.coffee
- tests/api/fixtures/tasks.coffee
- tests/api/tasks/check_entities.test.coffee
- tests/api/tasks/collect_entities.test.coffee
- tests/api/tasks/get.test.coffee
- tests/api/tasks/has_encyclopedia_occurence.test.coffee
- tests/api/tasks/hooks.test.coffee
- tests/api/tasks/update.test.coffee
- tests/api/utils/tasks.coffee
mainly by the introduction of a `check-entities` endpoint (0802afd) that allows to reliably test tasks creation without the hazards of `collect-entities` job creation
> improving tasks tests

- server/controllers/entities/lib/properties.coffee
- server/lib/wikidata/whitelisted_properties.coffee
and whitelisted SUDOC, ORCID IDs, and 'published in'
Adding SUDOC and ORCID IDs will allow to add those ids to inv entities, while just whitelisting 'published in' (P1433) will allow to display this relation on wd entities without supporting it for inv entities yet
> entities properties: added SUDOC and ORCID IDs

- server/controllers/entities/lib/update_inv_claim.coffee
- server/controllers/entities/lib/update_inv_label.coffee
- server/lib/retry_on_conflict.coffee
- tests/api/entities/update_claims.test.coffee
- tests/api/entities/update_labels.test.coffee
- tests/api/utils/entities.coffee
allow parallel requests to `/api/entities?action=update-claim` and `/api/entities?action=update-label` without throwing a conflict error.
This could come handy for when clients will implement one-click claim update such as adding authors from a list of suggestions: several edits could occur in a very short time span
> improve parallel entity editing

- server/controllers/items/lib/snapshot/get_entities.coffee
- server/controllers/items/lib/snapshot/refresh_snapshot.coffee
- tests/api/fixtures/entities.coffee
- tests/api/items/snapshot.test.coffee
- tests/api/utils/items.coffee
well, that was ugly
the issue was that [non-formatted edition docs (that is, without .image.url attribute) were used when refreshing snapshot following an event on the work](https://github.com/inventaire/inventaire/blob/a9fecad/server/controllers/items/lib/snapshot/refresh_snapshot.coffee#L67), creating this weird situation were snapshot refresh triggered by the edition returned with images but not when triggered from the work...
> Fix items snapshot image

- server/controllers/user/lib/geo/follow.coffee
- server/db/couch/init_design_doc_sync.coffee
- server/lib/follow.coffee
My dev setup was falling to update design docs files as requested by [`server/db/couch/init_design_doc_sync`](https://github.com/inventaire/inventaire/blob/aafa8b8/server/db/couch/init_design_doc_sync.coffee) when design docs on CouchDB change. After some joyful debugging, it appeared that it was because the leveldb-based `meta` db was keeping a `last_seq` value ahead of the current `last_seq`, thus never calling `onChange` functions despite new changes.
* 1a9aa84 fixes this by checking this kind of incoherence with the database before starting to follow changes
* 371da9a is then just a refactor of `reset` actions, currently only used by the users geo index
> Fix db follow

- server/controllers/entities/lib/find_author_from_works_labels.coffee
- server/controllers/entities/lib/get_works_labels_occurrence.coffee
- server/controllers/tasks/lib/automerge.coffee
- server/controllers/tasks/lib/build_task_docs.coffee
- tests/api/tasks/external_sources_occurrences.test.coffee
- rename `has_works_labels_occurrence` into `get_works_labels_occurrence` as
it doesn't return a simple boolean anymore but a collection of occurrences
- attach occurrences on suggestions objects to keep their context at hand
without having to handle those 2 parallel collections of objects
- change behavior when there are several suggestions but only one has occurrences: now automerges
> build_task_docs: refactor

- config/default.coffee
- server/controllers/entities/lib/get_entities_popularity.coffee
- server/controllers/entities/lib/get_wikidata_enriched_entities.coffee
- server/controllers/entities/lib/reverse_claims.coffee
- server/data/bnf/get_bnf_author_works_titles.coffee
- server/data/commons/thumb.coffee
- server/data/wikidata/run_query.coffee
- server/data/wikidata/search_entities.coffee
- server/data/wikipedia/get_article.coffee
- server/lib/cache.coffee
- tests/api/entities/popularity.test.coffee
- tests/unit/libs/037-cache.coffee
Make `cache_.get` use an object interface and integrate `cache_.dryGet` feature
(A [coming PR](https://github.com/inventaire/inventaire/pull/242) builds on those evolutions to cleanup popularity scores, splitting this code exploration in 2 PRs for clarity)
> cache cleanup

- server/controllers/entities/lib/get_popularity_by_uri.coffee
- server/controllers/entities/lib/reverse_claims.coffee
typically for editions properties, given that editions from Wikidata are still ignored
see #182
> reverse_claims: run requests on local entities only for certain properties

- server/controllers/entities/lib/get_entities_by_uris.coffee
- server/controllers/entities/lib/verify_that_entities_can_be_removed.coffee
- tests/api/entities/delete.test.coffee
due to a different URI being used by item.entity, typically an ISBN, while the `inv:` URI was passed
> entities delete by uris: fix issue with items not detected

- server/controllers/entities/lib/get_entities_popularity.coffee
- server/lib/cache.coffee
- tests/api/entities/popularity.test.coffee
- tests/api/search/search.test.coffee
- tests/api/utils/entities.coffee
- tests/unit/libs/037-cache.coffee
by making popularity score requests dry too: if a popularity score is in cache it will be used, otherwise, the popularity returns immediately with the default value (0), and a request to populate the score is triggered in the background
> speedup search

- server/controllers/tasks/lib/automerge.coffee
- server/controllers/tasks/lib/get_new_tasks.coffee
- tests/api/tasks/automerge.test.coffee
- tests/api/tasks/external_sources_occurrences.test.coffee
as occurences are not relevant since author name will mostly be
mentionned on source pages
renaming automerge variables
move tests to automerge test file
> task automerge: dont merge suspect when authorName is in WorkTitle

- server/controllers/entities/lib/find_author_from_works_labels.coffee
- server/controllers/entities/lib/get_occurences_from_entities.coffee
- server/controllers/entities/lib/get_occurrences_from_external_sources.coffee
- server/controllers/tasks/lib/add_occurrences_to_suggestion.coffee
- server/controllers/tasks/lib/add_occurrences_to_suggestions.coffee
- server/controllers/tasks/lib/automerge.coffee
- server/controllers/tasks/lib/get_new_tasks.coffee
- tests/api/tasks/automerge.test.coffee
this PR corrects some past decisions : 
- do not merge authors that have their names in their work (ie. an autobiography) since occurences found on external source page are the name of the author in question.
and add a couple a new way of finding occurences/clues
- to find potential suspect, it now checks if the suggestion ("wd:Q42") has inventaire works entity with the same label as the suspect works.
> Automerge when same work label

- server/controllers/entities/lib/placeholders.coffee
- server/controllers/entities/lib/remove_entities_by_inv_id.coffee
- server/controllers/tasks/lib/tasks.coffee
- tests/api/tasks/hooks.test.coffee
to avoid have old tasks hanging around while their suspect entity was removed already
> Archive removed placeholder tasks

- server/controllers/items/lib/snapshot/build_snapshot.coffee
- tests/api/fixtures/entities.coffee
- tests/api/items/snapshot.test.coffee
to be able to display subtitles without having to fetch the entity
typically in items lists
> items snapshot: snapshot editions' title

- server/data/wikidata/queries/serie_parts.coffee
- server/lib/cache.coffee
- tests/api/entities/popularity.test.coffee
- tests/unit/libs/037-cache.coffee
a loop was created by requesting the popularity of a serie having itself as part ([example](https://www.wikidata.org/w/index.php?title=Q56064945&oldid=726704275)), this is fixing it by filtering-out series' parts that are either the serie itself or which has the serie for part (f254da4)
Other commits are just fixing an undesired behavior of the cache (5795d5c) and fixing a test (10f3e24)
> prevent popularity infinite loop

- server/models/entity.coffee
- tests/unit/models/024-entity.coffee
to easily be able to access creation and last update dates for data cleaners, or from query.inventaire.io
> add entities timestamps

- server/controllers/entities/lib/get_occurrences_from_external_sources.coffee
- server/data/openlibrary/get_ol_author_works_titles.coffee
- tests/api/tasks/external_sources_occurrences.test.coffee
query OpenLibrary search API endpoint for every supected work titles
filter only works that have suggestion authorId
makes async API calls as usually works titles are not numerous
todo : make the cache working
> tasks: add open library checks

- server/controllers/items/bulk_update.coffee
- server/controllers/items/items.coffee
- server/controllers/items/lib/items.coffee
- server/lib/sanitize/parameters.coffee
- server/models/item.coffee
- server/models/validations/item.coffee
- server/models/validations/task.coffee
- tests/api/items/bulk-details.test.coffee
- tests/api/items/bulk-update.test.coffee
- tests/unit/models/023-item.coffee
open endpoint `bulk-update` for smoothing transition out of `update` and not breaking the api
import controller and model logic from [tasks](server/server/models/task.coffee)
> items:update-bulk update one attribute on many items

- server/controllers/entities/lib/revert_merge.coffee
- tests/api/entities/revert_merge.test.coffee
the recovery of placeholder after a `revert-merge` was mistakenly implemented from the start (missing argument), and there was no test to help spot it
---
Documenting what I had to do to recover failed placeholder recoveries:
* generate a ttl dump including `removed:placeholder`s by replacing
* [`serialize_entity_in_turtle.coffee#L9`](https://github.com/inventaire/inventaire/blob/978e338/scripts/dumps/lib/serialize_entity_in_turtle.coffee#L9) with `if type is 'removed:placeholder' then return "inv:#{_id} a wikibase:RemovedPlaceholder ."`
* [`prepare_entities_dumps#L46`](https://github.com/inventaire/inventaire/blob/978e338/scripts/dumps/prepare_entities_dumps#L46) with `grep '"type":"'`
* load the generated dump to a Blazegraph namespace:
```sh
curl …
```
> entities: revert-merge: fix and test placeholder recovery

- server/controllers/entities/create.coffee
- server/controllers/entities/lib/create_inv_entity.coffee
- server/controllers/entities/lib/create_wd_entity.coffee
- server/controllers/entities/lib/move_to_wikidata.coffee
- server/controllers/entities/lib/scaffold_entity_from_seed/edition.coffee
- server/controllers/entities/lib/scaffold_entity_from_seed/work.coffee
- server/controllers/entities/lib/update_wd_claim.coffee
- server/controllers/entities/lib/update_wd_label.coffee
- server/controllers/entities/lib/validate_entity.coffee
- server/controllers/entities/lib/wikidata_oauth.coffee
- server/lib/error/pre_filled.coffee
- server/lib/sanitize/parameters.coffee
- server/lib/sanitize/sanitize.coffee
- tests/api/entities/create.test.coffee
- tests/unit/libs/046-sanitize.coffee
having the possibility to create a wikidata item from `/api/entities?action=create` would allow the client to create missing entities when editing Wikidata entities.
Currently, that would fail, as we can only create inv entities, and those can't be added as claim values on Wikidata:
> create wikidata item

- server/controllers/entities/reverse_claims.coffee
- server/lib/sanitize/parameters.coffee
- tests/api/entities/reverse_claims.test.coffee
needed by the client to be able to resolve ids.
Example: find a publisher from an ISBN publisher prefix (`wdt:P3035`): `/api/entities?action=reverse-claims&property=wdt:P3035&value=978-2-505`
> reverse_claims: accept string values

- server/controllers/entities/lib/create_wd_entity.coffee
- server/controllers/entities/lib/move_to_wikidata.coffee
- server/controllers/entities/lib/validate_claim_value.coffee
- server/controllers/entities/lib/validate_claims.coffee
- server/controllers/entities/lib/validate_entity.coffee
those moves were rejected as the concurrency checks were finding the moved entity itself
This is for instance [preventing this entity to be moved to Wikidata](https://inventaire.io/entity/inv:60905d992c09c12f92b0a8a78ed0a41f/edit) has it has a [`wdt:P3035`](https://www.wikidata.org/entity/P3035) claim value already used by... itself, so concurrency tests fail at creating a new entity with that claim value. The patch is thus to pass a flag disabling the concurrency check when the validated entity is a (soon to be) Wikidata entity.
> entities: move_to_wikidata: fix case where moved entity has concurrent property claims

- server/controllers/entities/lib/get_serie_parts.coffee
- server/controllers/entities/lib/queries_utils.coffee
- server/data/wikidata/queries/serie_parts.coffee
* filter-out editions
* take ordinal data from serie claim qualifiers too
* push parts with subparts up the list
* keep a reference to superparts in subparts to let the client choose if they should be displayed or not
> improve serie parts query

- server/controllers/tasks/lib/check_entity.coffee
- tests/api/tasks/check_entities.test.coffee
the logic behind the endpoint is coupled to humans entry points.
This doesn't mean that this endpoint shouldn't support other types in the future, just that it currently doesn't do it well and should thus refuse to do it and return informative feedback to the requester.
> Restrict checked entities types

- server/controllers/entities/lib/resolver/resolve_on_labels.coffee
- tests/api/entities/resolver/resolve.test.coffee
More permissive resolver, by resolving work labels that match even if case is different. (`case-insensitive-work-resolver` could have been the other name of this branch.)
And on the way to get there a bug was found and fixed : before, every works resolved on labels no matter if the label matched or not. Every work resolved on every work...
> More permissive resolver

- server/controllers/entities/lib/get_authors_uris.coffee
- server/controllers/entities/lib/get_occurrences_from_entities.coffee
- server/controllers/entities/lib/get_occurrences_from_external_sources.coffee
- server/controllers/entities/lib/resolver/helpers.coffee
- server/controllers/entities/lib/resolver/resolve.coffee
- server/controllers/entities/lib/resolver/resolve_authors_from_works.coffee
- server/controllers/entities/lib/resolver/resolve_on_labels.coffee
- server/controllers/entities/lib/resolver/resolve_on_terms.coffee
- server/controllers/entities/lib/resolver/resolve_works_from_authors.coffee
- server/controllers/entities/lib/resolver/resolve_works_from_edition.coffee
- server/controllers/entities/lib/scaffold_entity_from_seed/work_entity_search_deduplicating_cache.coffee
- server/controllers/entities/lib/scaffold_entity_from_seed/work_entity_search_utils.coffee
- server/controllers/tasks/lib/automerge_author_works.coffee
- server/lib/utils/base.coffee
which boils down to using the `getEntityNormalizedTerms` on both existing entities and seeds, allowing to take entities aliases into account
> transform resolve_on_labels into resolve_on_terms

- package-lock.json
- package.json
Now that level-party got updated (#349), there wasn't much blocking us from updating to the latest Node LTS.
The only (minor) issue, was those `TimeoutOverflowWarning` warnings, due to old versions of `hyperquest` (see https://github.com/substack/hyperquest/issues/62) being depended on by `couch2elastic4sync` at various degrees. Using a custom version of `couch2elastic4sync` allows to depend on updated packages, until there is an official release with updated dependencies.
The `engine` in `package.json` being advisory, this PR is mostly a call to other contributors to udpate their version of Node and `rm -rf node_modules && npm install` (and be amazed at how faster it goes :D), and to be coordinated with:
- [`inventaire-client`](https://github.com/inventaire/inventaire-client/pull/190)
- …
> update node to v12 (latest LTS)

- server/db/couch/init.js
- server/lib/follow.js
- server/server.js
In this age of Docker containers, it now happens that a service is started and not another: making every code depending on it wait for CouchDB to be available, instead of assuming it is, allows to gracefully recover from a situation where the server was started before CouchDB.
> follow: prevent crash when CouchDB isn't yet available

- server/controllers/entities/reverse_claims.js
- server/controllers/entities/update_label.js
- server/controllers/groups/lib/update_settings.js
- server/controllers/items/bulk_update.js
- server/controllers/user/update.js
- server/lib/geo.js
- server/lib/sanitize/parameters.js
- server/models/group.js
- server/models/user.js
- tests/api/groups/create.test.js
- tests/api/groups/update_settings.test.js
- tests/api/user/update.test.js
it seems that as of this day, we are guilty of keeping position coordinates at the atomic level
cf https://xkcd.com/2170/
for context (and as I wasn't sure myself), we are dealing with decimal degrees, as [that's what browsers give us](https://developer.mozilla.org/en-US/docs/Web/API/GeolocationCoordinates)
while that's not exactly a bug, relying on such precise coordinates just adds noise
but this PR also fixes a bug: it's currently impossible to update a group position, any group update returns a 400, see de4f527 and 8a043f45
> truncate geographic positions

- server/controllers/items/lib/snapshot/update_snapshot_on_entity_change.js
- server/controllers/tasks/hooks.js
- server/controllers/tasks/lib/tasks.js
- server/models/attributes/task.js
- server/models/task.js
- tests/api/tasks/hooks.test.js
(I'm doing a cleanup of my old stashes, which sometimes have some useful bits (in CoffeeScript, yeay ><))
> recover tasks after entity merge was reverted

- server/controllers/images/gravatar.js
- server/controllers/images/images.js
- tests/api/images/gravatar.test.js
An endpoint to get the request user email and convert it to a gravatar url so that a client can offer to import an existing avatar
This endpoint is being depended on by https://github.com/inventaire/inventaire-client/pull/195
> add an endpoint to get the gravatar url corresponding to the email of the requesting user

- package-lock.json
- package.json
- server/lib/fs.js
by reverting commit b8b48d4
fix #375 , using the module `mv` rather than `fs-extra`, as it's way smaller
> fix media storage cross device EXDEV error

- server/controllers/entities/lib/resolver/create_entity_from_seed.js
- server/controllers/entities/lib/scaffold_entity_from_seed/work.js
- server/data/wikidata/queries/editions_reverse_claims.js
- tests/api/entities/create.test.js
- tests/api/fixtures/entities.js
- tests/unit/models/024-entity.js
- tests/unit/models/025-patch.js
Q571 as a P31 value has been deprecated for a while on Wikidata, meaning that [Wikidata items created from an inventaire.io import need to be fixed](https://editgroups.toolforge.org/b/wikibase-cli/cbcf544f2f519/). This patch fixes the problem at the source.
> replace wd:Q571 by wd:Q47461344 as default work P31

- server/controllers/entities/entities.js
- server/controllers/entities/lib/revert_edit.js
- server/controllers/entities/lib/revert_merge.js
- server/controllers/entities/revert_edit.js
- server/lib/boolean_validations.js
- server/lib/regex.js
- server/lib/sanitize/parameters.js
- server/models/validations/common.js
- tests/api/entities/revert_edit.test.js
- tests/api/utils/entities.js
addressing #408 
That was much easier than anticipated as all the work was already done for the needs of `/api/entities?action=revert-merge`
> entities: add a revert-edit endpoint

- server/models/user.js
- tests/unit/libs/044-slugify.js
keeping previous emails was initially added with the idea to cover the case where someone mistakenly changes their email to an invalid email, but with the side effect to keep more user data than explicitly allowed by the user. It was never used so far, so removing it seems like the right thing to do
> user model: updateEmail: do not keep previous emails

- config/default.js
- config/tests-integration.js
- server/lib/requests.js
- server/lib/requests_temporary_host_ban.js
- tests/integration/requests.js
Among the SPARQL endpoints the resolver makes requests to, there is one that currently refuses to answer anything, which always end-up with a timeout after 60 seconds, which makes eeeeeeeverything slow. This PR brings a mechanism to automatically identify hosts that fail to answer and temporarily ban requests to those, with a growing ban time
> temporarily stop to make requests to a host that answered with a timeout

- config/default.js
- config/tests-api.js
- config/tests-integration.js
- package-lock.json
- package.json
- scripts/test_integration
- server/controllers/entities/lib/entities.js
- server/controllers/entities/lib/entities_relations_temporary_cache.js
- server/controllers/entities/lib/get_author_works.js
- server/controllers/entities/lib/get_serie_parts.js
- server/controllers/entities/lib/merge_entities.js
- server/controllers/entities/lib/move_to_wikidata.js
- server/controllers/entities/lib/prefix.js
- server/controllers/entities/lib/temporarily_cache_relations.js
- server/controllers/entities/lib/turn_into_redirection.js
- server/controllers/entities/lib/update_wd_claim.js
- server/controllers/entities/merge.js
- server/controllers/tasks/lib/automerge.js
- server/controllers/tasks/lib/automerge_author_works.js
- server/db/level/get_sub_db.js
- server/lib/boolean_validations.js
- server/lib/wikidata/aliases.js
- tests/api/entities/get_by_uris.test.js
- tests/api/entities/merge.test.js
- tests/api/entities/move_to_wikidata.test.js
- tests/api/entities/temporarily_cache_relations.test.js
- tests/api/entities/update_claims.test.js
- tests/api/fixtures/entities.js
- tests/api/tasks/get.test.js
- tests/integration/entities_relations_temporary_cache.js
addressing #313 
The proposed implementation:
- puts the desired relations in a LevelDB db, from which they will be removed once their TTL expired (after 4 hours by default)
- checks that cache for graph queries (list of authors works or series parts), in addition to other sources (Wikidata and local entities)
> keep a temporary cache of relations that aren't yet available to the Wikidata Query Service

- config/tests-integration.js
- server/controllers/relations/lib/actions.js
- server/lib/radio.js
- tests/unit/libs/050-radio.js
this PR proposes to give the guaranty, in tests, that event listeners were executed before the HTTP response was sent, to avoid race conditions such as illustrated by https://github.com/inventaire/inventaire/pull/441#discussion_r516587600
How to use:
* replace `radio.emit` by `await radio.emit` to give that guaranty
* `tapEmit` always await in tests env
> radio: wait for async listeners in test environment

- server/controllers/user/lib/geo/follow.js
- server/lib/follow.js
This is an exploration of the opportunity to upgrade CouchDB from 1.7 to 3.1.
Upgrading to the 3.1 (the latest stable version) would bring [quite a few changes](https://docs.couchdb.org/en/stable/whatsnew/), especially:
- improved perf
- security patches
- adds [automatic compaction](https://docs.couchdb.org/en/stable/maintenance/compaction.html#compact-auto)
- updated SpiderMoney version: would allow to replace coffeescript views by modern JS syntax
- new recommended query language: Mango Query Server, see [`/db/_find`](https://docs.couchdb.org/en/stable/api/database/find.html#api-db-find)
- that's mostly an alternative syntax to map/reduce views, but with some indexation benefits in terms of perfs, and possibly a nicer developer experience
- Includes some interesting new pagination …
> upgrade CouchDB from 1.7 to 3.1

- scripts/dumps/lib/serialize_entity_in_turtle.js
- scripts/dumps/prepare_entities_dumps
- scripts/update_entities.js
- server/controllers/entities/lib/entities.js
- server/controllers/entities/lib/revert_merge.js
- server/lib/retry_on_conflict.js
- server/models/entity.js
- server/models/patch.js
- tests/api/entities/create.test.js
- tests/unit/models/024-entity.js
- tests/unit/models/025-patch.js
After restoring the entities database without documents revs ids, all entities got their `_rev` integer component reset to `1`, which meant that new edits on those entities triggered the creation of patches with the same id as an existing patch, which is thus rejected as a conflict.
This PR addresses the problem by creating a version number on entities independent from revs ids.
After merging, and **before** deploying:
- set a `version` number on all entities
- try to recover lost patches
> decouple patches ids from entities revs

- server/controllers/search/lib/entities_query_builder.js
fix #473 
tested with queries
"Jean baudrillard"
"Victor Hugo"
"Alexandre Dumas"
"Victor mees"
"Sanjay Gandhi"
on "All", "Author" and "Work"
one may see the score results by adding a function to `server/controllers/search/lib/type_search.js#L43` such as: 
```js
.then(foo => {
const bar = foo.hits.hits.map(f => {
return {
score: f._score,
label: f._source.labels.en || f._source.labels.fr || 'foo',
id: f._id
}
})
console.log('result', bar)
return foo
})
```
> 473 search decrease popularity relevance

- server/controllers/entities/by_uris_get.js
- server/controllers/entities/lib/get_entities_by_isbns.js
- tests/api/entities/get_by_uris.test.js
pass a boolean param (`existing`) to get_entity_by_uris to not trigger any creation when the requester does not want to create any entity when passing an isbn
known cases: checking if entity exists and/or if it has a cover before
uploading the image in order to feed the resolver with an `"invp:P2" : "imageHash"` from the media container only when necessary
> get existing entities by isbn

- package-lock.json
- package.json
- server/controllers/entities/lib/entities_relations_temporary_cache.js
- server/data/wikidata/queries/author_works.js
- server/data/wikidata/queries/editions_reverse_claims.js
- server/data/wikidata/queries/humans_reverse_claims.js
- server/data/wikidata/queries/publisher_collections.js
- server/data/wikidata/queries/queries.js
- server/data/wikidata/queries/serie_parts.js
- server/data/wikidata/queries/works_reverse_claims.js
- server/data/wikidata/run_query.js
- server/lib/cache.js
- tests/api/entities/temporarily_cache_relations.test.js
- tests/integration/entities_relations_temporary_cache.js
In the current situation:
- a user sets a P50 on a Wikidata entity from the Inventaire entity editor
- the [entities relations temporary cache](https://github.com/inventaire/inventaire/blob/a85f27d/server/controllers/entities/lib/temporarily_cache_relations.js) keeps that relation in memory for a certain time, so that when some user requests the entities having a P50 claim pointing to that same target entity, we can add to the result the value we are aware of, before the Query Service update
- after that time (4h by default), the relation is removed from the temporary cache **but** cached queries pre-dating the initial update might still be in the cache (can be seen with `lev ./db/level-tests --prefix '!cache!wdQuery'`), returning results we know to be out-dated
This PR makes sure that …
> more sophisticated invalidation of Wikidata Query Service cached results

- server/controllers/search/lib/entities_query_builder.js
Due to the `boost_mode=sum`, entities that have a high popularity some how pop up in results despite there lexical match being very low. Example: when searching "Jean Baudrillard", wd:Q182847 should arrive first, and certainly not arrive after the (glorious but irrelevant) René Goscinny (wd:Q192214) ahead of him
This PR proposes to come back to `modifier=ln2p` and the default `boost_mode=multiply`
> fix popularity boost in entities search

- server/controllers/entities/lib/find_author_from_works_labels.js
- server/controllers/entities/lib/resolver/resolve_on_terms.js
- server/controllers/entities/lib/scaffold_entity_from_seed/search_work_entity_by_title_and_authors.js
- server/controllers/search/lib/entities_query_builder.js
- server/controllers/tasks/lib/get_new_tasks.js
- server/db/elasticsearch/mappings/mappings_datatypes.js
- server/db/elasticsearch/settings/settings.js
- server/lib/elasticsearch.js
- tests/api/fixtures/entities.js
- tests/api/fixtures/text.js
- tests/api/search/entities.test.js
- tests/api/utils/search.js
fix #485 last issue, or at least makes the last failing test pass (without adding any new field or requiring a reindexation \o/)
We could still imagine cases where the exact match would have false positives, when terms are longer than 10 characters. For instance searching "Naturwissenschaft" would consider the following as exact matches:
- "Naturwissenschaftler"
- "Naturwissenschaftlerin"
- "naturwissenschaftlich"
- or just any term that matches `/naturwisse\w*/i`
But that looks like an acceptable compromise, as most `exact` requests involve several words (ex: "Metaphysische Anfangsgründe der Naturwissenschaft") that all have to be found in the field
TODO after merge:
- [update prod Elasticsearch indexes with the new settings](https://github.com/inventaire/inventaire/blob/4ebe2ae/server/db …
> find entities with terms longer than autocomplete max ngram

- server/controllers/entities/lib/merge_entities.js
- server/controllers/entities/lib/move_to_wikidata.js
- server/controllers/entities/lib/turn_into_redirection.js
to not be surprised each time a non-dataadmin user makes a merge this way
To fully complete its purpose, we would also need to have the client display patches context in history views
> move_to_wikidata: add context to the redirection patch

- server/controllers/search/lib/entities_query_builder.js
- server/db/elasticsearch/formatters/entity.js
- tests/api/search/entities.test.js
- tests/api/utils/search.js
- tests/unit/indexation/entity_formatter.js
- tests/unit/indexation/fixtures/Q535.customized.json
Flattened terms currently don't help much for matching due to the different analyzer used during indexation (which you can see with the test added in d71208f3), this PR fixes that by adding a dedicated query with the query-time analyzer matching the index-time analyzer. I also created [a branch to track changes we would like to do before the next full reindexation of entities](https://github.com/inventaire/inventaire/tree/entities-reindexation), which would align the analyzers, allowing to remove that new query.
This PR also proposes to remove terms already in the main fields from the flattened terms, as those are just dead weight 
76f3896
> entities indexation: fix flattened terms query

- server/controllers/items/lib/queries_commons.js
- server/controllers/transactions/lib/rights_verification.js
- server/controllers/transactions/lib/side_effects.js
- server/controllers/transactions/lib/transactions.js
- server/controllers/transactions/mark_as_read.js
- server/controllers/transactions/update_state.js
- server/db/couchdb/design_docs/transactions.json
- server/models/attributes/item.js
- tests/api/fixtures/transactions.js
- tests/api/transactions/request.test.js
- tests/api/transactions/update-state.test.js
- tests/api/utils/transactions.js
fix #492 by querying the transactions database to determine the state of `item.busy`
This PR is meant to not require any changes on the client: items requests will still return items with a `busy` flag.
But this also opens new possibilities for the future, such as setting the `busy` flag only when explicitly requested, or implementing a `include-transactions` flag (like the `include-users`)
> item busy state: replace derived data by query to the primary data

- server/controllers/glob.js
see https://plausible.io/blog/google-floc
This would need to be applied in [Nginx config](https://github.com/inventaire/inventaire-deploy/blob/master/nginx/inventaire.original.nginx#L291) too to be effective in production
> Opt-out from Google FLoC

- package-lock.json
- package.json
- server/controllers/entities/lib/scaffold_entity_from_seed/edition.js
- server/controllers/images/convert_url.js
- server/controllers/images/lib/containers.js
- server/controllers/images/lib/convert_image_url.js
- server/controllers/images/lib/download_file.js
- server/controllers/images/lib/import_image.js
- server/controllers/images/lib/is_valid_image_content_type.js
- server/controllers/images/upload.js
- server/data/isbn.js
- server/db/couchdb/design_docs/images.json
- server/db/couchdb/list.js
- server/lib/crypto.js
- server/lib/utils/base.js
- tests/api/images/convert_url.test.js
- tests/api/images/data_url.test.js
- tests/api/images/upload.test.js
- tests/api/items/export.test.js
- tests/api/utils/images.js
- tests/api/utils/request.js
Currently, when adding an edition cover (`invp:P2` claim) from a URL, the URL is sent to the server, which sends it to dataseed, which does several things:
1 - cleanup the URL from known services (ex: it would convert https://covers.openlibrary.org/b/id/7811996-M.jpg into https://covers.openlibrary.org/b/id/7811996-L.jpg to get the larger image)
2 - download the remote image, generate a sha1 hash of the file, and re-upload it to the media storage container with that hash as filename
3 - add the source URL and corresponding hash to a CouchDB database
This PR proposes to move the points 2 and 3 to the inventaire server, to get the following benefits:
- increase independence from dataseed, contributing to #481, as instances without access to a dataseed service could still use the …
> Convert image url locally

- server/controllers/entities/lib/get_occurrences_from_external_sources.js
- server/controllers/entities/lib/properties/properties_per_type.js
- server/controllers/entities/lib/terms_normalization.js
- server/data/gnd/get_gnd_author_works_titles.js
- server/lib/wikidata/allowlisted_properties.js
[GND is the database with the most ids known by Wikidata (around 1228395 at the moment)](https://query.wikidata.org/#%23%20Databases%20with%20a%20SPARQL%20endpoint%2C%20sorted%20by%20number%20of%20ids%20known%20by%20Wikidata%0ASELECT%20%3Fservice%20%3FserviceLabel%20%3Fproperty%20%3FpropertyLabel%20%3Fendpoint%20(COUNT(%3Fid)%20AS%20%3Fids_count)%20%20%7B%0A%20%20%3Fservice%20wdt%3AP5305%20%3Fendpoint%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20wdt%3AP1687%20%3Fproperty%20.%0A%20%20%3Fproperty%20wikibase%3AdirectClaim%20%3Fprop%20.%0A%20%20%3Fentity%20%3Fprop%20%3Fid%20.%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22.%20%7D%0A%7D%0AGROUP%20BY%20%3Fservice%20%3FserviceLabel%20%3Fproperty%20%3FpropertyLabel%20%3Fendpoint%0AORD …
> add GND as a data source to match authors works titles

- server/controllers/entities/lib/properties/properties_per_type.js
ex: I would like to be able to add the mastodon account `pourpenser@mamot.fr` on https://inventaire.io/entity/inv:3004a6b69ab86898047462cd2def90be like it can be done for authors already
> entities: properties_per_type: allow to set social networks claims on publishers and collections

- server/controllers/shelves/update.js
- server/lib/actions_controllers.js
This PR proposes to move controllers boilerplate to [`server/lib/actions_controllers.js`](https://github.com/inventaire/inventaire/blob/a930c1c/server/lib/actions_controllers.js), taking `server/controllers/shelves/update.js` as an example of what could be done (leaving the application in bulk of this new format to another PR)
> controllers deboilerplatification

- server/controllers/entities/entities.js
- server/controllers/entities/history.js
- server/controllers/user/lib/authorized_user_data_pickers.js
- server/controllers/user/update.js
- server/db/couchdb/hard_coded_documents.js
- server/lib/actions_controllers.js
- server/lib/user_access_levels.js
- server/models/attributes/user.js
- server/models/user.js
- server/models/validations/user.js
- tests/api/entities/history.test.js
- tests/api/fixtures/users.js
- tests/api/user/update.test.js
- tests/api/utils/utils.js
Currently, entities history is only accessible by admins. This PR propose to open it to all, while keeping the data of the user that made the edit (a.k.a. contributor) private by default. The reasoning being that we want to preserve privacy by default, and that users might not know that when they add a subject to a work, they are actually editing a public wiki. This PR also allows to opt-in for public contributions by updating a setting on the user document. We could then recommend to regular contributors to opt-in, via the Wiki documentation and/or directly on the editor.
Client PR: #275
> make entities history publicly accessible, while keeping contributors data private by default

- server/controllers/search/search.js
- server/lib/actions_controllers.js
- server/lib/controller_wrapper.js
- server/lib/sanitize/sanitize.js
- tests/unit/libs/046-sanitize.js
* allows to declare endpoints in a deboilerplatified way, even when not passing by `ActionsControllers`
Bonus:
* remove last bits of `sanitizeAsync`
> controllers: extract non-action-related logic from ActionsControllers function

- server/lib/requests.js
- server/middlewares/middlewares.js
- server/middlewares/security.js
- server/middlewares/statics.js
- tests/api/middlewares/cors.test.js
Addressing #301
* accept preflight requests by always returning a 200 with `access-control-allow-*` headers to `OPTIONS` requests
* open all public resources to cross-domain request
* deny access to resources requiring authentication by advising browsers to not include session cookies in cross-domain requests (by setting `access-control-allow-credentials=false`), to prevent CSRF
Authenticated requests from third party apps should then rather pass by OAuth tokens #84
> CORS policy update

- server/controllers/search/lib/entities_query_builder.js
- server/db/elasticsearch/formatters/entity.js
- server/db/elasticsearch/mappings/entities.js
- server/db/elasticsearch/mappings/mappings_datatypes.js
- tests/api/fixtures/entities.js
- tests/api/search/entities.test.js
addressing #213, among other cases (see commit messages)
This PR supposes to reindex entities, so should ideally be grouped with other changes requiring a reindexation, such as 56f41af (included in this PR) and #530
> search: allow to search entities with their relative entities labels

- server/controllers/search/lib/entities_query_builder.js
- server/controllers/search/lib/type_search.js
- server/controllers/search/search.js
- server/db/elasticsearch/formatters/entity.js
- server/db/elasticsearch/mappings/entities.js
- server/db/elasticsearch/mappings/mappings_datatypes.js
- server/lib/sanitize/parameters.js
- tests/api/search/entities.test.js
- tests/api/search/search.test.js
- tests/api/search/search_entities.test.js
- tests/api/search/search_entities_by_claim.test.js
- tests/api/utils/search.js
This PR proposes a first implementation of search claim filters, inspired by [Wikibase `haswbstatement`](https://www.mediawiki.org/wiki/Help:Extension:WikibaseCirrusSearch#haswbstatement).
Implemented:
~~* [ ] `NOT`~~ (maybe it's fine to let that one out from this PR?)
Those filters would allow, for instance, to add search fields on authors layouts: in that example, the `claim` parameter would be set to `wdt:P50=${author.uri}` (or actually more probably `wdt:P50=${author.uri}|wdt:P58=${author.uri}|wdt:P110=${author.uri}|wdt:P6338=${author.uri}` to be complete)
This branch is based on `213-relations-search`, so most commits displayed below at the time of this message actually belong to #529, which should thus be considered first
> search claim filter

- server/lib/emails/email.js
as they are likely not aware that the email they used to signup to inventaire is being leaked when inviting people
> invitations email: prevent leaking user email

- server/controllers/entities/lib/resolver/helpers.js
- server/controllers/entities/lib/resolver/resolve_authors_from_works.js
- server/controllers/entities/lib/resolver/resolve_by_external_ids.js
- server/controllers/entities/lib/resolver/resolve_works_from_authors.js
- server/controllers/entities/lib/resolver/resolve_works_from_edition.js
- server/data/bnb/get_bnb_entry_from_isbn.js
- server/data/bne/get_bne_entry_from_isbn.js
- server/data/bnf/get_bnf_entry_from_isbn.js
- server/data/lib/external_ids.js
- tests/integration/data/get_resolved_entry.js
The kind of error this is trying to address (logs from prod main server, starting at `Sep 20 19:45:56`):
```js
****** next entry ******
{
edition: {
isbn: '9788877992925',
claims: {
'wdt:P1476': [ 'La donazione di Costantino' ],
'wdt:P268': [ '42479597n' ],
'wdt:P407': [ 'wd:Q397' ]
},
labels: {}
},
works: [
{
uri: 'wd:Q238476',
labels: { fr: 'Donation de Constantin' },
claims: { 'wdt:P268': [ '123807414' ] }
}
],
authors: []
}
-----
****** inv entity creation ******
{
labels: {},
claims: {
'wdt:P31': [ 'wd:Q3331189' ],
'wdt:P629': [ 'wd:Q238476' ],
'wdt:P212': [ '978-88-7799-292-5' ],
'invp:P2': [ 'c51bb8a2ade9980d14416d3f575d806d8d3ffa43' ],
'wdt:P1476': [ 'La donazione di Costantino' ],
'wdt:P268': [ '42479597n' ],
'wdt:P407': [ 'wd:Q397' ]
},
userId: …
```
> validate authorities entries entity types before passing it to the resolver

- server/controllers/activitypub/activity.js
- server/controllers/activitypub/follow.js
- server/controllers/activitypub/inbox.js
- server/controllers/activitypub/lib/entity_patch_activities.js
- server/controllers/activitypub/lib/format_entity_patches_activities.js
- server/controllers/activitypub/lib/get_actor.js
- server/controllers/activitypub/lib/helpers.js
- server/controllers/activitypub/lib/post_activity.js
- server/controllers/activitypub/lib/radio_hooks.js
- server/controllers/activitypub/lib/security.js
- server/controllers/activitypub/outbox.js
- server/controllers/activitypub/undo.js
- server/lib/sanitize/parameters.js
- tests/api/activitypub/activity.test.js
- tests/api/activitypub/actor.test.js
- tests/api/activitypub/inbox_undo.test.js
- tests/api/activitypub/outbox.test.js
a PR that makes various follow up after https://github.com/inventaire/inventaire/pull/552 https://github.com/inventaire/inventaire/pull/554 https://github.com/inventaire/inventaire/pull/544
remaining todo:
- implement `/api/activitypub?action=activity` for shelves activities
> activity pub follow-ups

- server/lib/wikidata/allowlisted_properties.js
Not including those properties might give the false impression that no claim exists for that property, thus invite to set it while one might already exist.
Example of an edit that should not have been done: https://www.wikidata.org/w/index.php?title=Q39052974&type=revision&diff=1526384437&oldid=1526384409
Properties that were missing:
P112
P127
P243
P437
P571
P576
P1025
P1143
P1182
P1274
P1292
P5199
P5571
> wikidata allowlisted_properties: include all properties that can be edited from Inventaire

- server/lib/sanitize/parameters.js
- tests/api/invitations/by_emails.test.js
as the message is optional anyway
> invitations: by_email: do not throw when an empty string is sent as message

- server/controllers/auth/connection.js
- server/controllers/auth/token.js
- server/controllers/entities/images.js
- server/controllers/feeds/feeds.js
- server/controllers/invitations/by_emails.js
- server/controllers/items/export.js
- server/controllers/transactions/update_state.js
- server/lib/controller_wrapper.js
- server/lib/sanitize/parameters.js
- server/lib/sanitize/sanitize.js
- tests/unit/libs/046-sanitize.js
Does 2 features were coded together but do not depend on each others (could be splitted, if one is blocking)
Allow to use a well known sanitization parameter (ex: `password`) with a prefix (ex: `new`) without having to set yet another parameter in `server/lib/sanitize/parameters.js`
Until this, if a controller was trying to use parameter not defined in `server/lib/sanitize/parameters.js`, that bug would only be raised when a user would make a request.
> sanitization: parameter aliases and config validation at start-up

- server/controllers/entities/lib/create_inv_entity.js
- server/controllers/entities/lib/entities.js
to prevent having blank entities hanging in the database when the creation crashes due to, for instance, a missing wdt:P629 on an edition (we had 500 of those in the database before I deleted them today)
> create_inv_entity: skip creation of a blank entity

- server/controllers/entities/entities.js
- server/controllers/entities/history.js
- server/controllers/entities/lib/restore_version.js
- server/controllers/entities/restore_version.js
- tests/api/entities/restore.test.js
- tests/api/utils/entities.js
continuing on #408
This would be useful to revert what seems to be repeated mistakes(?) of a user that used existing editions to turn them into completely different editions ([example](https://inventaire.io/entity/isbn:9782035858603/history)). Reverting one edit at a time makes the operation somewhat tedious, and the history unnecessarily big and hard to read (example [1](https://inventaire.io/entity/isbn:9782226062130/history), [2](https://inventaire.io/entity/isbn:9782070322831/history))
> entities: add restore-version endpoint

- server/controllers/activitypub/lib/build_attachements.js
- server/controllers/activitypub/lib/get_actor.js
- server/controllers/activitypub/lib/helpers.js
- server/controllers/activitypub/lib/platforms.js
- server/controllers/activitypub/lib/properties_display.js
- tests/api/activitypub/actor.test.js
roughly addressing #579 
check it on the sandbox, ie. searching for @wd-Q84352@sandbox.inventaire.io
properties translations do not seem to work on sandbox (in prod either?)
missing features: - ebooks, - authors birth and death - summary when no description
> Add claims attachements to entity actors

- server/controllers/entities/lib/create_wd_entity.js
- server/controllers/entities/lib/entities_relations_temporary_cache.js
- server/controllers/entities/lib/queries_utils.js
- server/controllers/entities/lib/update_wd_claim.js
- server/lib/wikidata/data_model_adapter.js
- server/lib/wikidata/format_claims.js
- tests/api/entities/get_by_uris.test.js
- tests/unit/libs/051-wikidata_data_model_converter.js
Addressing #433 the hacky way, until we get to support qualifiers #145 
P1545 being set as claims instead of qualifiers of P179 has been a recurring problem, more and more pressing as it was generating quite some frustration from the Wikidata community ([latest example](https://www.wikidata.org/wiki/User_talk:Fitz_Loinvoyant#Serial_ordinal)): this hacky fix would relieve the pressure and let us either take our time to implement qualifiers, or not implement it at all.
As for any operation editing Wikidata, writing automated tests is hard, so here are the manual tests for `update-claim`:
- [set a P1545 qualifier](https://www.wikidata.org/w/index.php?title=Q4115189&diff=1538602121&oldid=1538601961)
- [update an existing P1545 qualifier](https://www.wikidata.org/w/index.php?title=Q4115189&diff …
> convert P1545 claims into qualifiers of P179 on-the-fly

- server/controllers/entities/contributions.js
- server/controllers/entities/lib/patches.js
- server/db/couchdb/design_docs/patches.js
- tests/api/entities/contributions.test.js
A useful tool for administrators to misinformed edits on a precise property: my current use-case is a user having change many `wdt:P629`, and those would need to be reverted, but it needs to be done manually as some entities were further edited.
This PR depends on #585 for convenience, but could be rewritten without it if #585 was to get stuck
> allow to filter contributions by claim property or label lang

- server/controllers/entities/lib/restore_version.js
- server/controllers/entities/lib/revert_edit.js
- server/controllers/entities/lib/update_inv_claim.js
- server/controllers/entities/lib/update_inv_label.js
- server/controllers/entities/lib/update_label.js
- server/controllers/items/lib/snapshot/update_snapshot_on_entity_change.js
- tests/api/items/snapshot.test.js
namely, `revert-edit` and `restore-version`, which were not taken into account, leading to obsolete snapshot data after those operations.
The other commits are just small cleanups while being around
> refresh items snapshots after new entity operations

- server/controllers/entities/by_uris_get.js
- server/controllers/entities/lib/pick_attributes.js
- server/controllers/entities/lib/pick_props.js
- server/lib/sanitize/parameters.js
- tests/api/entities/get_by_uris.test.js
Currently, when a piece of UI wants to display some basic info on an entity (typically a label, a description, a uri, and an image), it has to fetch the whole formatted entity, which might include way more data than needed (ex: https://inventaire.io/api/entities?action=by-uris&uris=wd:Q535).
This PR suggests to add a ~`props`~ [edit: `attributes`] and a `lang` parameter to the `/api/entities?action=by-uris` endpoint to let the client request just what it needs.
> Prevent over-fetching when fetching entities basic info

- server/controllers/search/lib/entities_query_builder.js
- server/db/elasticsearch/formatters/entity.js
- server/db/elasticsearch/mappings/entities.js
- server/db/elasticsearch/mappings/mappings_datatypes.js
- server/db/elasticsearch/settings/analyzers.js
- server/db/elasticsearch/settings/filters.js
- server/db/elasticsearch/settings/settings.js
- tests/api/search/search_entities.test.js
- tests/api/search/search_entities_by_claim.test.js
- tests/api/utils/search.js
- tests/integration/elasticsearch/entities_analyzers.js
This is done by indexing entities' labels and aliases a second time, but this time without applying the edge n-gram filter, to be able to perform exact search on them.
Example of a failed exact search (that should be fixed by this PR): [an exact search for "Norberto bob"](https://inventaire.io/api/search?types=humans&search=Norberto%20bob&lang=en&exact=true) should not find "Norberto Bobbio" (`wd:Q332693`)
While duplicating labels and aliases does have a cost in terms of index size, it would greatly improve features depending on exact search such as "merge suggestion" in the client or the resolver on the server.
This PR also addresses the single-word issue previously addressed in #517
> entities search: prevent exact match to include non-exact matches due to edge n-gram tokens

- config/default.js
- config/tests-api-server.js
- server/controllers/tasks/collect_entities.js
- server/lib/os.js
to let the priority to more urgent matters, such as answering users requests
> tasks: collect_entities: wait for CPUs load to be below 50% to run the worker

- server/controllers/shelves/create.js
- tests/api/shelves/create.test.js
'items' params was already allowlisted but nothing was done with it
this PR allows shelf to be created with their items
should ease client issue [#253](https://github.com/inventaire/inventaire-client/issues/253)
> create shelf with items

- package-lock.json
- package.json
- server/controllers/entities/lib/get_occurrences_from_external_sources.js
Use-case: prevent missing occurrences of work titles in Wikipedia articles due to close but different characters being used by the different inputs. For instance, `Charte de l’environnement` is not the same as `Charte de l'environnement` and wouldn't count as an occurrence in the current implementation.
This PR introduces a new dependency, but a tiny one, and based on the same Lucene ASCIIFoldingFilter class we use through Elasticsearch `asciifolding` filter.
> createOccurrencesFromUnstructuredArticle: normalize terms using ascii folding

- server/controllers/entities/lib/entities.js
- server/controllers/entities/lib/format_entity_common.js
- server/db/elasticsearch/formatters/entity.js
- tests/api/entities/get_by_uris.test.js
to allow not over-fetching claims but still get a label when requesting `attributes=labels`
Useful for https://github.com/inventaire/inventaire-client/pull/311
> entities by-uris: set editions and collections terms from claims

- server/controllers/activitypub/webfinger.js
- server/lib/boolean_validations.js
- server/lib/sanitize/parameters.js
- tests/api/activitypub/webfinger.test.js
- tests/unit/libs/055-boolean_validations.js
Currently, only resources in the form `acct:georges@inventaire.io` are accepted, rejecting resources in the form `https://inventaire.io/api/activitypub?action=actor&name=georges`
By accepting resources in the URL form, this PR would allow to answer with a 200 instead of a 400 to requests such as
```
GET /.well-known/webfinger?resource=https%3A%2F%2Finventaire.io%2Fapi%2Factivitypub%3Faction%3Dactor%26name%3Dgeorges 400
```
Such requests can be seen in the server logs, with Friendica in their user agent: I hope solving this would solve the issues reported lately (in mastodon DM) with Friendica integration
> Add support for actor url webfinger as resource

- config/default.js
- config/tests-api-server.js
- server/controllers/entities/lib/resolver/resolve_update_and_create.js
- server/controllers/entities/resolve.js
- server/controllers/tasks/collect_entities.js
in order to let the server breath when resolving hundreds of uris with a long import (maybe prepmature optimization, but server have better things to do than resolving when under pressure)
> make resolver nice

- server/data/dataseed/get_resolved_entry.js
- server/lib/temporarily_memoize.js
- tests/api/entities/get_by_uris.test.js
- tests/unit/libs/056-temporarily_memoize.js
Making several calls to `GET /api/entities?action=by-uris` with `autocreate=true` can trigger the creation of duplicated edition entities. There seem to currently be more than 1600 in the production database. The reason for that is likely to be that the importer now seems to regularly trigger simultaneous requests for the same isbn-identified edition. Requests examples:
```
Sep 26 11:47:50 prod: GET /api/entities?action=by-uris&uris=isbn:9782738108074&refresh=false&autocreate=true 200 4465ms
Sep 26 11:47:50 prod: GET /api/entities?action=by-uris&uris=isbn:9782738108074&refresh=false&relatives=wdt:P629|wdt:P50&autocreate=true 200 664ms
```
which produces the following entities:
https://inventaire.io/entity/inv:76a0f40371636ef9184d3fdccd5778b5/history …
> prevent the creation of several editions with the same isbn, when in autocreate mode

- server/controllers/entities/contributions.js
- server/controllers/entities/history.js
- server/controllers/entities/lib/anonymize_patches.js
- tests/api/entities/contributions.test.js
- tests/api/entities/history.test.js
do not anonymize patches from the requesting user when requested by the history and contributions endpoints, so that the requesting user can see their contributions, even when their privacy settings do not let other user see them
> patches: do not anonymize patches from the requesting user

- server/controllers/items/by_users.js
- server/controllers/items/lib/queries_commons.js
- server/controllers/listings/by_creators.js
- server/lib/sanitize/parameters.js
- server/models/validations/item.js
- server/models/validations/listing.js
- server/models/validations/shelf.js
- server/models/validations/visibility.js
- tests/api/items/get_by_users.test.js
- tests/api/listings/by_creators.test.js
Currently, the main user private listings are displayed in every contexts, which can be confusing. This PR proposes to update the former `filter` parameter used for items into a `context` parameter, that takes a visibility key, and deduces what items or listings should not be returned for a given query, even if the requesting user has access rights.
> Implement context tailored listings

- server/controllers/entities/lib/special_entity_images_getter.js
- server/db/elasticsearch/formatters/entity.js
Client publisher layout needs to illustrate a preview of collection covers:
Following the work and series way to do it
This is a make it work implementation.
A server delivering already crafted images object is nice, but at the cost of querying all editions... Maybe having the client request editions covers would make more sense to take advantage of caching the editions (?)
> Add collection images special getter

- server/lib/elasticsearch.js
- server/lib/sanitize/parameters.js
- server/lib/search_by_position.js
- tests/api/fixtures/users.js
- tests/api/users/search_by_position.test.js
to make the map usable by people on the [Taveuni island](https://www.openstreetmap.org/#map=10/-16.8151/-179.8325), or more generally, to display users/groups/items between islands in the Pacific ocean.
Useful map to make sense of all those latitude/longitude coordinates:
This PR generally assumes that we are only supporting people sharing books on Earth.
> Allow to search by position with a bbox overlapping the anti-meridian

- server/controllers/shelves/by_ids.js
- server/controllers/shelves/lib/shelves.js
- tests/api/shelves/delete.test.js
~Based on #664 to avoid conflicts.~
After merge:
* check prod items database for obsolete shelf ids
> remove shelf id from item.shelves when deleting a shelf

- server/controllers/entities/images.js
- server/controllers/entities/lib/get_entities_images.js
- tests/api/entities/images.test.js
- tests/api/fixtures/entities.js
This PR updates the API endpoint `/entities?action=images` so that entities with a special getter (work, collection and series) which previously responded with
```
"wd:Q535": [ 'Victor Hugo by Étienne Carjat 1876 - full.jpg' ]
```
are now responding with:
```
"wd:Q535": { claims: [ 'Victor Hugo by Étienne Carjat 1876 - full.jpg' ] }
```
> Entities images harmonization

- server/controllers/entities/lib/properties/properties_config_builders.js
- server/controllers/entities/lib/properties/properties_values_constraints.js
- server/controllers/entities/lib/validate_claim_value_sync.js
- tests/api/entities/update_inv_claims.test.js
- tests/api/fixtures/entities.js
Currently, if you enter a BNF id with its `cb` prefix (ex: `cb10317178p`), it is refused. This PR fixes that by adding a `format` function.
> Be more tolerant on BNF ids format

- server/controllers/data/lib/summaries/sitelinks.js
- server/controllers/entities/lib/add_image_data.js
- server/controllers/entities/lib/get_occurrences_from_external_sources.js
- server/controllers/entities/lib/get_wikidata_enriched_entities.js
- tests/api/data/summaries.test.js
Example: this summary should not be displayed https://inventaire.io/entity/wd:Q3020076?lang=fr
TODO post-PR-merge, invalidate Wikidata entities cache:
```sh
lev db/leveldb_cache-prod --prefix 'wd:enriched:' --del | lev db/leveldb_cache-prod --batch
```
> entities summaries: ignore sitelinks that are redirections

- server/controllers/entities/entities.js
- server/controllers/entities/remove_label.js
- server/controllers/entities/update_label.js
- server/models/entity.js
- tests/api/entities/remove_label.test.js
- tests/api/entities/update_inv_labels.test.js
- tests/api/utils/entities.js
- tests/unit/models/024-entity.js
This is currently not possible, which can be an issue in cases where a label was set in a language where there is no label for a given work. Example: [this work](https://inventaire.io/api/entities?action=by-uris&uris=inv:320d4c7c453886081a4da182e3d1e512) has a label in Catalan but no know label in Spanish, thus the attempt by a contributor to delete the Spanish label.
> entities: update-label: allow to delete a label

- server/controllers/user/lib/authorized_user_data_pickers.js
- server/controllers/user/lib/is_reserved_word.js
- server/controllers/users/by_creation_date.js
- server/controllers/users/lib/users.js
- server/controllers/users/users.js
- tests/api/users/by_creation_date.js
To simplify the work of casually checking the kind of activity going on. The need arised in development (as I wanted to easy recover a user I had created to continue to play with its particuliar case), but could typically be useful to observe the latest spammers' tricks in prod
Client PR: https://github.com/inventaire/inventaire-client/pull/412
Fixes #455
> users: add admin-only endpoint to fetch the latest created users

- server/controllers/entities/lib/resolver/resolve_by_external_ids.js
- server/controllers/entities/lib/resolver/resolve_edition.js
- server/controllers/entities/lib/resolver/resolve_external_ids.js
- server/data/bnf/get_bnf_entry_from_isbn.js
- server/data/bnf/helpers.js
- tests/integration/data/get_bnf_entry_from_isbn.test.js
Namely: translators, preface and postface authors
> get_bnf_entry_from_isbn: add edition contributors

- server/controllers/items/lib/queries_commons.js
- tests/api/items/get_by_ids.test.js
This should prevent "unauthorized shelves access" errors that you see on items that belong to shelves you are not authorized to access. Example: https://inventaire.io/items/4519939c6c5fb623a53e04e57a3ef551
> items: remove shelves ids that the requesting user is not authorized to access

- server/controllers/entities/by_uris_get.js
- server/controllers/entities/lib/popularity.js
- tests/api/entities/get_by_uris.test.js
- tests/api/utils/entities.js
This would allow to simplify code such as `getAndAssignPopularity` in https://github.com/inventaire/inventaire-client/pull/384 by getting popularities straight from the call to `getEntitiesAttributesByUris`:
ex: `GET /api/entities?action=by-uris&attributes=type|labels|popularity&uris=wd:Q535`
> /api/entities?action=by-uris: attach entities popularities when requested

- scripts/populate_users_fixtures.js
- server/controllers/data/wp_extract.js
- server/controllers/entities/lib/get_occurrences_from_entities.js
- server/controllers/entities/lib/get_occurrences_from_external_sources.js
- server/controllers/entities/lib/resolver/resolve_on_terms.js
- server/controllers/tasks/lib/automerge.js
- server/controllers/tasks/lib/check_entity.js
- server/controllers/tasks/lib/deduplicate_works.js
- server/controllers/tasks/lib/find_authors_with_isbns_in_wikipedia_articles.js
- server/controllers/tasks/lib/get_new_tasks.js
- server/controllers/tasks/lib/tasks.js
- server/data/wikipedia/get_article.js
- server/lib/isbn/isbn.js
- server/lib/promises.js
- tests/api/tasks/automerge.test.js
- tests/api/tasks/hooks.test.js
Adding two more criteria to the new tasks validations (happening when triggering `check-entities`)
It will ends up merging automatically more entities, and reduce the number of new tasks created.
- 6d3ad81 Merging based on WD structured data (external IDs claims). This could have been a maintenance sparql query, but automerge automates it nicely. Known case: inv entity had had an externalId before wd item
- d0ccd3e Merge if author's ISBNs appears in their related wikipedia article. This relies on cached wp page. The cost is to request author's graph to fetch isbns.
> Automerge on claims

- server/controllers/data/lib/summaries/bnf.js
- server/controllers/data/lib/summaries/getters.js
- server/controllers/data/lib/summaries/openlibrary.js
- tests/api/data/summaries.test.js
- tests/api/utils/entities.js
In the current implementation, OpenLibrary summaries are only fetched when there is a know OpenLibrary identifier, but summaries for editions could also be fetched by ISBN
> get Openlibrary summaries by ISBN

- server/controllers/entities/lib/get_entities_by_isbns.js
- server/controllers/entities/lib/resolver/create_entity_from_seed.js
- server/controllers/entities/lib/resolver/helpers.js
- server/controllers/entities/lib/resolver/resolve_edition_from_works.js
- server/controllers/entities/lib/resolver/update_resolved_entry.js
- server/data/dataseed/enrich_and_get_edition_entity_from_isbn.js
- server/data/dataseed/get_authorities_aggregated_entry.js
- tests/api/entities/resolver/resolve_and_create.test.js
- tests/api/entities/resolver/resolve_and_update.test.js
- tests/integration/data/enrich_and_get_edition_entity_from_isbn.test.js
Currently, external databases (aka authorities) are checked when there is no entity in the local database for a given ISBN. The proposed change would be to re-check those external databases for existing edition entities when requested, that is when `autocreate=true&refresh=true`.
Writing a test is unfortunately not so straight forward, as you would need to create an edition/work/author with the right labels, so that the resolver can confidently update those entities. But as I expect it to become a popular feature from data admins, I'm sure we will notice if this breaks somehow ;)
Client PR https://github.com/inventaire/inventaire-client/pull/482
> get_entities_by_isbns: refresh seeds when requested

- config/default.cjs
- config/production-alt.cjs
- package-lock.json
- package.json
- server/controllers/entities/lib/create_wd_entity.ts
- server/controllers/entities/lib/get_entities_by_isbns.ts
- server/controllers/entities/lib/move_to_wikidata.ts
- server/controllers/entities/lib/resolver/resolve_edition.ts
- server/controllers/entities/lib/resolver/update_resolved_entry.ts
- server/controllers/entities/lib/special_entity_images_getter.ts
- server/controllers/entities/lib/update_inv_claim.ts
- server/controllers/entities/lib/update_wd_claim.ts
- server/controllers/entities/lib/update_wd_entity_local_claims.ts
- server/controllers/entities/lib/wikidata_oauth.ts
- server/controllers/user/lib/user.ts
- server/db/couchdb/hard_coded_documents.ts
- server/lib/user_access_levels.ts
- server/lib/wikidata/data_model_adapter.ts
- server/lib/wikidata/edit.ts
- server/types/config.ts
- server/types/user.ts
- tests/api/entities/resolver/resolve.test.ts
- tests/api/entities/resolver/resolve_and_update.test.ts
- tests/api/search/indexation_entities.test.ts
- tests/unit/libs/wikidata_data_model_converter.ts
Now that the server takes Wikidata editions into account (#753) and that it should soon be possible to move local entities  to Wikidata (#760), a missing brick was the possibility to perform the same kind of data enrichment we do on local entities directly on Wikidata entities, so that's what PR tries to do.
This is unfortunately hard to test as we don't mock edits on Wikidata, so Let's Test In Prod™ and see if further adjustments are needed.
One requirement was to make the resolver able to resolve to Wikidata editions, which is the other part of this PR.
~~PR based on #760~~
> Allow the resolver to update Wikidata entities

- server/controllers/listings/create.ts
- server/controllers/listings/lib/listings.ts
- server/models/attributes/listing.ts
- server/models/listing.ts
- server/models/validations/listing.ts
- server/types/listing.ts
- tests/api/listings/add_elements.test.ts
- tests/api/listings/create.test.ts
Add a `type` key (maybe `entitiesType` is more DSL friendly?) on Listing model.
Solves issue #716
client PR [502](https://github.com/inventaire/inventaire-client/pull/502)
> Listing entities type

- server/controllers/activitypub/follow.ts
- server/controllers/activitypub/lib/activities.ts
- server/controllers/activitypub/lib/build_attachments.ts
- server/controllers/activitypub/lib/entity_patch_activities.ts
- server/controllers/activitypub/lib/format_entity_patches_activities.ts
- server/controllers/activitypub/lib/format_items_activities.ts
- server/controllers/activitypub/lib/format_shelf_items_activities.ts
- server/controllers/activitypub/lib/format_user_items_activities.ts
- server/controllers/activitypub/lib/get_actor.ts
- server/controllers/activitypub/lib/helpers.ts
- server/controllers/activitypub/lib/post_activity.ts
- server/controllers/activitypub/lib/radio_hooks.ts
- server/db/couchdb/design_docs/activities.ts
- server/models/activity.ts
- server/types/activity.ts
- server/types/shelf.ts
- tests/api/activitypub/followers_activity_delivery.test.ts
- tests/api/activitypub/inbox_follow.test.ts
- tests/api/utils/activitypub.ts
This PR allows posting `Accept` and `Create` activities to shared inboxes when available.
The difficulty was to refactor `signAndPostActivities` (renamed `postActivities`) to be able to build `body.to` array per instances. While I could not figure out in the documentation if this was necessary, it seems more logical to have adequate `body.to` (aka list of followers + a `Public` element)
This PR also adds some types on the ActivityPub part (related to #706), which is why it should be merged before any other [AP related PRs](https://wiki.inventaire.io/wiki/NGI_Zero_Discovery_grants#3._Push_forward_ActivityPub)
Solves #575
> Shared inbox delivery

- server/controllers/listings/lib/elements.ts
- server/controllers/listings/lib/listings.ts
- server/controllers/listings/update_element.ts
- server/lib/utils/lexicographic_ordinal.ts
- server/models/element.ts
- server/types/listing.ts
- tests/api/fixtures/listings.ts
- tests/api/listings/update_element.test.ts
This PR updates the element's foreign key `list`, which will have the effect of moving the element to another list, called the `recipient list`.
Moving to another list is not authorised if an element with the same URI is already existing in the recipient list, which avoids dealing with potential comment be erased (and element removal).
Goes with client PR https://github.com/inventaire/inventaire-client/pull/523
To be merged after #752
> Listing move element

- server/controllers/groups/lib/groups.ts
- server/controllers/items/by_bbox.ts
- server/controllers/items/items.ts
- server/controllers/items/lib/filter_maximum_items_per_owner.ts
- server/controllers/items/recent_public.ts
- server/controllers/user/lib/user.ts
- server/controllers/users/search_by_position.ts
- server/lib/elasticsearch.ts
- server/lib/sanitize/parameters.ts
- server/lib/search_by_distance.ts
- server/lib/search_by_position.ts
- server/types/common.ts
- tests/api/fixtures/users.ts
- tests/api/items/get_by_bbox.test.ts
This is mainly opening a `items/by-bbox` endpoint in order to serve the client landing page map [#527](https://github.com/inventaire/inventaire-client/pull/527)
This seems cleaner than going through the existing `by-position` endpoint, since the client is displaying the exact books of users displayed on the map, while `by-position` would serve every item within a range/radius, ending potentially displaying items which do not belong to anyone on the map.
> Landing map

- package-lock.json
- package.json
- server/controllers/entities/lib/create_wd_entity.ts
- server/controllers/entities/lib/move_to_wikidata.ts
- server/controllers/entities/lib/update_wd_claim.ts
- server/controllers/entities/lib/update_wd_label.ts
- server/controllers/entities/lib/wikidata_oauth.ts
- server/lib/federation/remote_user.ts
The current motivation is to let federated users perform edits on Wikidata without having to connect their account, as the Wikidata OAuth workflow would require their local instance to have their own OAuth consumer tokens
But it's also nice for local users who might not want to create a Wikidata account, and can just edit from the very safeguarded Inventaire edition environment
This is a follow up to #796 
Example of an edit made by a user without Wikidata credentials: https://www.wikidata.org/w/index.php?title=Q112795079&diff=2304878238&oldid=2304858745
Client PR: https://github.com/inventaire/inventaire-client/pull/531
> Let local and federated users without Wikidata OAuth credentials edit Wikidata entities, by using the Wikidata bot account credentials

- config/default.cjs
- server/controllers/activitypub/follow.ts
- server/controllers/activitypub/lib/post_activity.ts
- server/controllers/activitypub/lib/security.ts
- server/types/activity.ts
- server/types/config.ts
- tests/api/activitypub/inbox_follow.test.ts
This PR allows the server to retry posting activities on remote instances after failing. 
It relies on function `initJobQueue` and leveldb in the background to achieve this.
Solves #719
To be merged after https://github.com/inventaire/inventaire/pull/801
> Activity jobs delivery
