- fr.json
> move 'le saviez-vous' to 'astuces'

- server/controllers/entities/lib/get_serie_parts.coffee
- server/controllers/entities/lib/queries_utils.coffee
- server/controllers/items/lib/snapshot/build_snapshot.coffee
- server/controllers/items/lib/snapshot/snapshot_entity_data.coffee
- server/data/wikidata/queries/serie_parts.coffee
Rename 'rank' to 'ordinal' to be consistent with Wikidata
> Rename rank to ordinal

- config/default.coffee
- config/tests.coffee
- server/lib/crypto.coffee
- server/lib/password_hashing.coffee
to make signup run faster in test environment
> crypto: allowing to disable password hashing

- api_tests/fixtures/items.coffee
- api_tests/fixtures/populate.coffee
- api_tests/items/create.test.coffee
- server/controllers/items/create.coffee
- server/controllers/items/lib/items.coffee
- server/controllers/items/lib/snapshot/snapshot_entity_data.coffee
- server/controllers/items/lib/update_entity.coffee
- server/controllers/user/lib/keep_snapshot_items_counts_updated.coffee
and make use of it to speed-up fixture `populate` function
> added bulk item creation

- server/controllers/entities/lib/properties.coffee
- server/lib/wikidata/whitelisted_properties.coffee
see associated [client PR](https://github.com/inventaire/inventaire-client/pull/123/commits/5864bab5acc11950e1948a9b1ce854ef71166704)
> cleaning and whitelisting new properties

- server/controllers/entities/lib/get_avatars_from_claims.coffee
to mutualize platforms logic and add Instagram
Outsourcing to avatars.io the task to stay up to date with the different platforms APIs
> entities get_avatars_from_claims: make use of avatars.io

- server/controllers/entities/lib/has_works_labels_occurrence.coffee
- server/data/bnf/get_bnf_author_works_titles.coffee
- server/lib/wikidata/whitelisted_properties.coffee
in addition to checking on Wikipedia
> also check authors works labels occurrences on BNF

- server/controllers/entities/lib/patches.coffee
instead of doing it in the server, which was highly inefficient for large sets of rows
Fetching contributions from users with 10,000+ contributions was triggering timeouts,
now it's done within 50ms
[This PR is given a "low priority" label has this only affects admins]
> patches byUserId: refactored to let CouchDB do the pagination work

- api_tests/entities/delete.test.coffee
- api_tests/entities/editions/update_labels.test.coffee
- api_tests/entities/get.test.coffee
- api_tests/entities/merge.test.coffee
- api_tests/entities/popularity.coffee
- api_tests/entities/reverse_claims.test.coffee
- api_tests/entities/revert_merge.test.coffee
- api_tests/entities/update_claims_hooks.test.coffee
- api_tests/fixtures/entities.coffee
- api_tests/items/create.test.coffee
- api_tests/items/snapshot.test.coffee
- api_tests/utils/entities.coffee
- api_tests/utils/items.coffee
- db/couchdb/design_docs/patches.json
- server/controllers/entities/lib/entities.coffee
- server/controllers/entities/lib/merge_entities.coffee
- server/controllers/entities/lib/patches.coffee
- server/controllers/entities/lib/placeholders.coffee
- server/controllers/entities/lib/redirect_claims.coffee
- server/controllers/entities/lib/revert_merge.coffee
- server/controllers/entities/lib/update_inv_claim.coffee
- server/controllers/entities/lib/update_label.coffee
- server/controllers/entities/merge.coffee
- server/models/patch.coffee
- test/models/025-patch.coffee
- also revert side-effects that weren't redirected yet: claims transfer, claims redirections
- added tests
> Revert merge clean up

- server/controllers/search/lib/query_body_builder.coffee
remove last term boost
add match_phrase and match_phrase_prefix
to boost the whole query instead of individual terms
> improve elastic search query

- api_tests/entities/merge.test.coffee
- server/controllers/entities/merge.coffee
in two cases:
- when 2 entities got created with the same ISBN (which should happen a lot less, if ever, since 25677b8, but is needed at the moment to address #168). This required to make the merger resolve non-canonical URIs (inv URIs) as the canonical URI in that case is the same for both entities
- when an entity with an ISBN is merged into an entity without ISBN in which case, the second entity get transfered the ISBN
Meanwhile, it should still reject merges between two edition entities with a different ISBN.
> entities merge: allow to merge entities with ISBNs

- package.json
- scripts/populate_fixtures
- scripts/populate_users_fixtures.coffee
- scripts/replicate_tests_db.coffee
- tests/api/fixtures/populate.coffee
- tests/api/items/recent_public.test.coffee
Scripts that POST `/_replicate` on couchdb 
from `*-tests` databases to `*`
an unobstrusive default replicate behavior
> Populate tests fixtures

- server/db/couch/init_hard_coded_documents.coffee
I could confirm the issue: when starting CouchDB and the server together with docker-compose, running init_hard_coded_documents with parallel update consistently returns a 401
> init_hard_coded_documents: init docs sequentially

- server/controllers/entities/lib/properties.coffee
- server/models/entity.coffee
and adding wdt:P1476 as a critical claim: edition entities (the only entities with wdt:P1476 yet)
should have a title, it can't be removed.
> entity model: declare critical claims in the properties params

- server/controllers/comments/lib/comments.coffee
- server/controllers/items/lib/delete_user_items.coffee
- server/controllers/user/delete.coffee
- server/lib/responses.coffee
- tests/api/user/delete.test.coffee
cleaning to prevent a 500 error because of a [missing `comments_` variable](https://github.com/inventaire/inventaire/blob/bf45de0/server/controllers/comments/lib/comments.coffee)
> Fix user delete

- db/couchdb/design_docs/users.json
this would fix https://inventaire.io/users/reconciler/contributions
> included hard-coded users in byUsername view

- package-lock.json
- package.json
- server/controllers/groups/lib/counts.coffee
- server/controllers/groups/lib/get_slug.coffee
- server/controllers/groups/lib/group_public_data.coffee
- server/controllers/groups/lib/groups.coffee
- server/controllers/groups/lib/leave_groups.coffee
- server/controllers/groups/lib/update_settings.coffee
- server/controllers/groups/lib/users_lists.coffee
- server/controllers/groups/public_actions.coffee
- server/controllers/user/lib/user.coffee
- server/lib/by_position.coffee
- tests/api/fixtures/groups.coffee
- tests/api/fixtures/users.coffee
- tests/api/groups/search_by_position.test.coffee
- tests/api/users/search_by_position.test.coffee
- group search-by-position action was returning a 500 because the response wasn't wrapped
- users where using an outdated design_doc view
adding tests
> users & groups: fix search by position

- server/controllers/entities/exists_or_create_from_seed.coffee
- server/lib/sanitize/parameters.coffee
- tests/api/entities/exists-or-create-from-seed.test.coffee
- tests/api/fixtures/entities.coffee
add authors and isbn as sanitize parameters
add tests with isbns sample in fixtures
> sanitize endpoint exists or create from from seed

- db/couchdb/design_docs/items.json
- server/controllers/items/lib/bundle_owners_to_items.coffee
- server/controllers/items/lib/items.coffee
- server/controllers/items/recent_public.coffee
- tests/api/items/recent_public.test.coffee
uses `publicByDate` couch view in order to fill recent items as `publicByLangAndDate` is now obsolete
> Fix recent public items

- server/controllers/entities/lib/scaffold_entity_from_seed/search_work_entity_by_title_and_authors.coffee
- server/controllers/entities/lib/scaffold_entity_from_seed/work_entity_search_utils.coffee
- tests/unit/libs/048-work_entity_search_utils.coffee
so that all volume editions don't end up being linked to the same work
addressing #90
> work_entity_search_utils: matchTitle: be more strict on title matching for volume titles

- server/controllers/search/lib/type_search.coffee
- server/controllers/search/search.coffee
- server/lib/sanitize/parameters.coffee
- tests/api/search/search.test.coffee
before those changes, whatever the request limit, only 20 results where taken from ElasticSearch
>  search: allow to customize the limit

- server/controllers/entities/lib/properties/properties_per_type.coffee
- server/controllers/entities/lib/properties/properties_values_constraints.coffee
- server/controllers/entities/lib/reverse_claims.coffee
- server/controllers/entities/search_type.coffee
- server/lib/wikidata/aliases.coffee
- tests/api/entities/create.test.coffee
- tests/api/entities/editions/create.test.coffee
- tests/api/entities/editions/update_labels.test.coffee
- tests/api/entities/exists-or-create-from-seed.test.coffee
- tests/api/entities/publishers/create.coffee
- tests/api/entities/search.test.coffee
- tests/api/entities/search_type.test.coffee
- tests/api/fixtures/entities.coffee
- tests/api/search/search.test.coffee
- tests/api/tasks/automerge.test.coffee
- tests/api/tasks/external_sources_occurrences.test.coffee
minimal attempt of creating and updating inventaire publishers
addressing #155
> [issue #155] Create inventaire publishers

- server/controllers/transactions/request.coffee
- server/models/transaction.coffee
- tests/api/fixtures/entities.coffee
- tests/api/fixtures/transactions.coffee
- tests/api/transactions/request.test.coffee
as the removal of item snapshot from the item doc broke the previous implementation
extend test to check the transaction snapshot data
> transactions: snapshot: fix entity snapshot

- server/lib/utils/base.coffee
- tests/unit/libs/035-utils.coffee
use:
```coffee
_ = __.require 'builders', 'utils'
_.mapKeysValues { a: 1, b: 2 }, (key, value)-> [ key.toUpperCase(), value * 2 ]
```
> add mapKeysValues helper

- server/controllers/entities/lib/properties/properties_per_type.coffee
- server/controllers/entities/lib/properties/properties_values_constraints.coffee
- server/lib/wikidata/whitelisted_properties.coffee
way more identifiers !
way more linked data possibilities !
woot
> Entities new properties

- server/data/wikidata/make_sparql_request.coffee
- server/data/wikidata/queries/humans_reverse_claims.coffee
- server/data/wikidata/queries/works_reverse_claims.coffee
the prod server got stuck with 4000+ queries waiting because some request failed and never decremented the ongoing count, this PR tries to address that
> fix sparql requests queue

- tests/api/entities/update_labels.test.js
- tests/api/groups/create.test.js
- tests/api/items/get_by_ids.test.js
- tests/api/transactions/get_messages.test.js
- tests/api/transactions/mark_as_read.test.js
- tests/api/transactions/post_message.test.js
- tests/api/transactions/request.test.js
- tests/api/transactions/update-state.test.js
- tests/api/user/delete.test.js
- tests/api/users/by_ids.test.js
- tests/api/users/by_username.test.js
- tests/unit/models/027-group.js
- tests/unit/utils.js
> rename shouldNotGetHere => shouldNotBeCalled

- server/controllers/items/export.js
- server/controllers/items/lib/export/csv_header_row.js
- server/controllers/items/lib/export/format_item_row.js
- tests/api/items/export.test.js
Implementation proposal for #431
> add shelves data to csv export

- server/controllers/notifications.js
- tests/api/notifications/get.test.js
I tried my hand at paginating the notifications as requested in #361
This is my first time working with this stack so I may have missed something. I used code similar to what I've found for the other APIs.
I found a corresponding test file, but I haven't found any way of actually running it (yet).
Comments and pointers welcome so I can improve :)
> paginate notifications

- server/controllers/groups/create.js
- server/models/attributes/group.js
- server/models/group.js
- server/models/validations/group.js
- tests/api/fixtures/groups.js
- tests/api/groups/create.test.js
- tests/api/groups/request.test.js
- tests/api/groups/update_settings.test.js
- tests/unit/models/027-group.js
> implement open groups

- tests/api/fixtures/groups.js
- tests/api/groups/search_by_position.test.js
specify a test to avoid its failure when to many groups are already created with the same location
> Improve tests groups

- server/controllers/extensions_redirections.js
- server/controllers/feeds/feeds.js
- server/controllers/feeds/lib/generate_feed_from_feed_data.js
- server/controllers/feeds/lib/group_feed_data.js
- server/controllers/feeds/lib/shelf_feed_data.js
- server/controllers/feeds/lib/user_feed_data.js
- server/controllers/groups/lib/groups.js
- server/lib/sanitize/parameters.js
- server/lib/sanitize/sanitize.js
- server/models/group.js
- tests/api/feeds/get.test.js
- tests/api/fixtures/items.js
- tests/api/fixtures/shelves.js
- tests/api/items/get_by_ids.test.js
- tests/api/redirections/rss.test.js
- tests/api/shelves/delete.test.js
- tests/api/shelves/remove_items.test.js
- tests/api/utils/shelves.js
following a request from a user who would like to use that feed to display a shelf on a Wordpress
> add shelves rss feeds

- server/controllers/entities/lib/resolver/update_resolved_entry.js
- tests/api/entities/resolver/resolve_and_update.test.js
- tests/api/fixtures/entities.js
solve #506 
if entry date is more precise, update the entity
> Resolver update date

- server/controllers/activitypub/lib/get_actor.js
- server/controllers/activitypub/lib/security.js
- server/lib/track.js
fixup commit got somehow lost into the limbs of an unknown rebase...
> activity-pub: re-apply review comment

- server/controllers/search/lib/entities_query_builder.js
- server/controllers/search/lib/type_search.js
`cross_fields` matching was disabled by 99a28ab02 to prevent the occasional crashes (see https://github.com/elastic/elasticsearch/issues/44700), but is actually critical to resolving https://github.com/inventaire/inventaire/issues/213 thus this compromise: default to `cross_fields`, but if the request to Elasticsearch fails, fall back to `best_fields`
> search: recover from cross_fields search errors

- server/controllers/entities/lib/get_wikidata_enriched_entities.js
- server/controllers/entities/merge.js
- server/controllers/feedback.js
- server/controllers/groups/lib/model_action.js
- server/controllers/invitations/lib/send_invitations.js
- server/controllers/transactions/lib/transactions.js
- server/controllers/user/lib/token.js
- server/lib/radio.js
to prevent counter-intuitive chains of events when testing
> generalize awaiting radio.emit calls

- scripts/dumps/prepare_entities_dumps
> entities dumps cleanup

- server/controllers/auth/update_password.js
- server/lib/sanitize/sanitize.js
- tests/api/auth/update_password.test.js
- tests/api/fixtures/users.js
depends on #566 for the use of the `current-password` parameter
> update-password: cleanup errors & refactor

- server/controllers/activitypub/actor.js
- server/controllers/activitypub/lib/get_actor.js
- server/controllers/activitypub/lib/get_actor_html_url.js
- server/controllers/activitypub/lib/helpers.js
- server/lib/controller_wrapper.js
- tests/api/activitypub/actor.test.js
addressing https://github.com/inventaire/inventaire/issues/577
> redirect accept=text/html requests to actors main url

- server/controllers/shelves/create.js
- server/controllers/shelves/lib/shelves.js
- server/controllers/shelves/update.js
- server/lib/boolean_validations.js
- server/lib/regex.js
- server/lib/sanitize/parameters.js
- server/models/attributes/shelf.js
- server/models/shelf.js
- server/models/validations/shelf.js
- tests/api/shelves/create.test.js
- tests/api/shelves/update.test.js
addressing #428 the minimalist way
> shelves create/update: allow to set a color attribute

- package.json
- server/controllers/entities/lib/revert_merge.js
- server/controllers/groups/lib/get_next_slug_candidate.js
- server/controllers/images/lib/convert_image_url.js
- server/db/couchdb/design_docs/transactions.js
- server/lib/emails/build_transaction_email.js
- tests/api/entities/resolver/resolve_and_update.test.js
- tests/api/entities/revert_edit.test.js
- tests/api/images/gravatar.test.js
- tests/api/invitations/by_emails.test.js
- tests/api/items/export.test.js
- tests/api/items/inventory_view.test.js
- tests/unit/models/024-entity.js
as made possible in NodeJS >= v16.6 ([currently the latest LTS](https://github.com/nodejs/Release#readme))
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at
> replace .slice(-1)[0] and _.last by .at(-1)

- server/controllers/entities/lib/properties/properties_per_type.js
- server/controllers/entities/lib/properties/properties_values_constraints.js
`wdt:P244` in particular is already [assumed to be available](https://github.com/inventaire/inventaire/search?q=wdt:P244&type=code)
> add Library of Congress properties wdt:P244 and wdt:P1144

- server/controllers/entities/contributions.js
- server/controllers/entities/entities.js
- server/controllers/entities/history.js
- server/controllers/entities/lib/anonymize_patches.js
- server/lib/sanitize/sanitize.js
- server/lib/user_access_levels.js
- server/models/user.js
- tests/api/entities/contributions.test.js
this PR depends on #511, and in itself contains only 1 commit (4b7101ca), the others belonging to #511
> allow to make entities contributions public

- config/default.js
- config/tests-api.js
- server/controllers/activitypub/inbox.js
- server/controllers/activitypub/lib/get_actor.js
- server/controllers/activitypub/lib/post_activity.js
- server/controllers/activitypub/lib/radio_hooks.js
- server/controllers/activitypub/lib/shared_key_pair.js
- server/controllers/items/lib/items.js
- server/lib/crypto.js
- server/lib/error/error_handler.js
- server/lib/requests.js
- server/lib/sanitize/parameters.js
- server/lib/sanitize/sanitize.js
- tests/api/activitypub/activity.test.js
- tests/api/activitypub/actor.test.js
- tests/api/activitypub/followers_activity_delivery.test.js
- tests/api/activitypub/outbox.test.js
- tests/api/activitypub/signed_request.test.js
- tests/api/utils/activitypub.js
- tests/unit/libs/046-sanitize.js
attempting to reduce the amount of failed signature verifications
> activitypub tweaks

- server/controllers/notifications/lib/group_update.js
- server/lib/emails/check_user_notifications_settings.js
- server/lib/emails/email.js
- server/lib/emails/mailer.js
- server/lib/emails/send_email.js
- server/lib/emails/transporter.js
- server/lib/emails/views/group_join_request.hbs
- server/lib/emails/views/partials/button_bottom.hbs
- server/lib/emails/views/partials/footer.hbs
- server/lib/emails/views/partials/general_info_bottom.hbs
- server/lib/emails/views/partials/header.hbs
- server/lib/emails/views/partials/image.hbs
- server/lib/emails/views/partials/paragraph_bottom.hbs
- server/lib/emails/views/partials/row_centered_bottom.hbs
- server/lib/emails/views/partials/row_top.hbs
- server/lib/emails/views/partials/title_bottom.hbs
- server/models/attributes/user.js
addressing #274 
The main commit is 147943ca, the rest is divers cleanups.
- Client side: https://github.com/inventaire/inventaire-client/pull/302
- i18n: https://github.com/inventaire/inventaire-i18n/pull/7
> send an email notification to group admins on requests to join the group

- server/controllers/entities/lib/resolver/resolve_on_terms.js
- server/controllers/search/lib/entities_query_builder.js
- server/controllers/search/lib/type_search.js
- server/controllers/search/search.js
- server/controllers/tasks/lib/get_new_tasks.js
- server/lib/elasticsearch.js
- tests/api/search/search_entities.test.js
- tests/api/utils/search.js
by accepting an offset parameter and returning total and continue values
> entities search: add pagination support

- server/controllers/auth/connection.js
- server/lib/regex.js
- server/lib/sanitize/parameters.js
- server/lib/utils/base.js
- server/models/user.js
- tests/api/auth/login.test.js
- tests/api/auth/signup.test.js
- tests/api/fixtures/users.js
- tests/api/user/update.test.js
- tests/unit/models/022-user.js
addressing https://github.com/inventaire/inventaire/issues/610
client PR: https://github.com/inventaire/inventaire-client/pull/315
> allow unicode usernames

- server/models/attributes/user.js
- server/models/validations/user.js
- tests/api/user/update.test.js
in relation with client PR [#339](https://github.com/inventaire/inventaire-client/pull/339)
> add a server persistent customization properties setting

- server/controllers/extensions_redirections.js
- tests/api/redirections/json.test.js
as a best effort instead of returning an invalid uri error
> redirect claim uri to its entity value

- config/default.cjs
- server/controllers/config.js
- server/controllers/reports/reports.js
- server/lib/utils/logs.js
* send a list of suspect keywords in client config
* customize error logging for user abuses
Client PR: https://github.com/inventaire/inventaire-client/pull/389
Based on #664 to avoid conflicts
> attempt to discourage spam accounts

- server/controllers/entities/lib/propagate_redirection.js
- server/controllers/listings/by_creators.js
- server/controllers/listings/by_entities.js
- server/controllers/listings/by_id.js
- server/controllers/listings/delete_by_ids.js
- server/controllers/listings/lib/elements.js
- server/controllers/listings/lib/listings.js
- server/controllers/listings/lib/update_element_uri.js
- server/controllers/listings/remove_elements.js
- server/models/element.js
- tests/api/listings/by_id.test.js
- tests/api/listings/by_ids.test.js
- tests/api/listings/delete.test.js
- tests/api/listings/remove_elements.test.js
A command line to check if there are redirections missing in prod
`curljson "LH:5984/elements-tests/_all_docs?include_docs=true" | jq -r ".rows[].doc.uri|." | xargs -I'@@' curl -H 'Content-Type:application/json' -H 'Accept: application/json' "LH:3009/api/entities?action=by-uris&uris={@@}" | jq '.redirects|select(length > 0)'`
> Propagate listing elements redirections

- server/controllers/transactions/update_state.js
- tests/api/transactions/update-state.test.js
Used by https://github.com/inventaire/inventaire-client/pull/472
> transactions: update-state: return the updated transaction

- tests/api/entities/duplicates.test.ts
- tests/api/entities/publisher_publications.test.ts
- tests/api/entities/resolver/resolve.test.ts
- tests/api/search/search_entities.test.ts
> Tests cleanup

- server/controllers/entities/lib/create_wd_entity.ts
- server/controllers/entities/lib/get_author_works.ts
- server/controllers/entities/lib/get_publisher_publications.ts
- server/controllers/entities/lib/get_serie_parts.ts
- server/controllers/entities/lib/inv_claims_utils.ts
- server/controllers/entities/lib/move_to_wikidata.ts
- server/controllers/entities/lib/properties/properties.ts
- server/controllers/entities/lib/queries_utils.ts
- server/controllers/entities/lib/resolver/resolve.ts
- server/controllers/entities/lib/resolver/resolve_by_external_ids.ts
- server/controllers/entities/lib/resolver/resolve_edition.ts
- server/controllers/entities/lib/resolver/resolve_external_ids.ts
- server/controllers/entities/lib/reverse_claims.ts
- server/data/bnf/helpers.ts
- server/data/wikidata/queries/author_works.ts
- server/data/wikidata/queries/editions_reverse_claims.ts
- server/data/wikidata/queries/humans_reverse_claims.ts
- server/data/wikidata/queries/publisher_collections.ts
- server/data/wikidata/queries/queries.ts
- server/data/wikidata/queries/resolve_external_ids.ts
- server/data/wikidata/queries/serie_parts.ts
- server/data/wikidata/queries/works_reverse_claims.ts
- server/data/wikidata/run_query.ts
- server/lib/utils/base.ts
- server/types/entity.ts
- tests/integration/entities_relations_temporary_cache.ts
- tests/unit/libs/wikidata_data_model_converter.ts
Addresses #704 
Client PR: https://github.com/inventaire/inventaire-client/pull/507
TODO after merge:
> allow moving editions and publisher collections to wikidata

- server/controllers/tasks/by_entities_type.ts
- server/controllers/tasks/get_tasks_count.ts
- server/controllers/tasks/lib/tasks.ts
- server/controllers/tasks/tasks.ts
- server/db/couchdb/design_docs/tasks.ts
- tests/api/tasks/tasks_count.ts
- tests/api/utils/tasks.ts
Solving [#724](https://github.com/inventaire/inventaire/issues/724)
Client PR [#516](https://github.com/inventaire/inventaire-client/pull/516)
Should be merged after #778
> Tasks dashboard

- server/controllers/listings/by_element_id.ts
- server/controllers/listings/listings.ts
- server/controllers/listings/update_element.ts
- server/models/element.ts
- server/types/element.ts
- tests/api/listings/by_element_id.test.ts
- tests/api/listings/remove_elements.test.ts
- tests/api/listings/update_element.test.ts
- tests/unit/models/element.ts
Should be rebased and merged after #677 is merged on main.
Most of the work is [client sided](https://github.com/inventaire/inventaire-client/pull/501)
> Listing element comment

- server/controllers/activitypub/activity.ts
- server/controllers/activitypub/lib/helpers.ts
- server/controllers/activitypub/webfinger.ts
- server/lib/memory_cache_public_controller.ts
to mitiage Fediverse DDoS seen in prod
> Cache public activitypub controllers
